### ISSUE TITLE
Mouse selection of text in text inputs does not work in Chrome

### ISSUE THREAD

**Issue by grantm** [grantm/jquery-udraggable#14]
After calling `.udraggable()`, any text inputs in the page - including outside the draggable area - no longer respond to mouse click-drag to select text

**Comment by grantm** [comment]
Looks like this is probably a duplicate of issue #9

**Comment by djkarimi** [comment]
Now I am doing guys?
Anyone solved this problem?
Please Help Me !!!
Go look this is link click : http://off.farazma.ir/ (Just Open Google Chrome ).

:(
