### ISSUE TITLE
is it possible to udraggable two divs?

### ISSUE THREAD

**Issue by petrospap** [grantm/jquery-udraggable#15]
Hello
Is it possible to udraggable two divs at the same time and also to get the values of css top offset, left offset both of them?

**Comment by grantm** [comment]
If you want one drag operation to move two divs by the same amount, the easiest approach would be to emulate the last example at the bottom of [this page](http://grantm.github.io/jquery-udraggable/examples/options.html#handle). The two divs would be in a container div; you'd apply udraggable to the container; and use the handle option with a class applied to the two divs to make them drag handles.
Alternatively, you could use a [drag callback](http://grantm.github.io/jquery-udraggable/examples/options.html#callbacks) to track the movements of one div and apply the same offsets to the other div.

When you supply a drag callback the positioning offsets are supplied in the ['ui' argument](http://grantm.github.io/jquery-udraggable/#drag) to your function.

**Comment by petrospap** [comment]
Thanks grantm
I finish my function to this
```
$('.dice1, dice2').udraggable({
        containment: 'parent',
        handle:      '.dot',
	   positionElement: function ($el, dragging, x, y) {
			if (dragging) {
				var dice1 = $( ".dice1" );
				var dice1Pos = dice1.position();

				var stepTop = dice1Pos.top - y;
				var stepLeft = dice1Pos.left - x;

				var dice2 = $( ".dice2" );
				var dice2Pos = dice2.position();
				
					$el.css({top: y + 'px', left: x + 'px'});
					$('.dice2').css({top: dice2Pos.top - stepTop + 'px', left: dice2Pos.left - stepLeft + 'px'});
			}
	     }

})
```
