### ISSUE TITLE
Disable / enable methods break previously set options

### ISSUE THREAD

**Issue by justingrounds** [grantm/jquery-udraggable#16]
Hello Grant, thank for a great draggable solution.
I'm using the disable and enable methods to reactivate udraggable on an element that is shown and hidden multiple times. I'm also using the axis & handle options so that the element that is dragged child elements work on mobile. However, I find that the disable / enable methods disable the options too?
It is draggable again, but without the options applied.
Any help would be much appreciated, thanks.

Website:
https://entrepreneurmap.com

Code I'm using to control the draggable element.
(function ($) {
	  $.each(['show', 'hide'], function (i, ev) {
	    var el = $.fn[ev];
	    $.fn[ev] = function () {
	      this.trigger(ev);
	      return el.apply(this, arguments);
	    };
	  });
})(jQuery);
$('#speccon').on('show', function(){
    $('#speccon').udraggable('enable');
	$("#speccon").udraggable({
	axis: 'y',
    handle: '.mhandle'
	});
});
$('#speccon').on('hide', function(){
    $('#speccon').udraggable('disable');
});

**Comment by grantm** [comment]
The problem in this example is that:

    $('#speccon').udraggable('enable');

Is called before:

    $("#speccon").udraggable({
        axis: 'y',
        handle: '.mhandle'
    });

I don't think that the second call belongs in the handler for the 'show' event.  The whole point of the 'enable' and 'disable' methods is that the options specified in the initial call to udraggable() will be preserved. But in your sample code you don't try and set up the initial options until *after* the 'enable' method was called.

When you first call udraggable() and pass it your desired set of options, those options are stored in an object which is attached to the DOM element. Later udraggable method calls will retrieve this object and call methods on it.

However, if you call a udraggable method (e.g.: 'enable') before setting the options, there is no object attached to the DOM element.  So the plugin will create a new object with all the default settings (no drag handle and no axis constraint), attach it to the DOM element and then call the method you specified.

The right place to initialise the udraggable options is when the `#speccon` element is created. It might make sense in you case to then immediately call `.udraggable('disable')` - I'm not sure.

**Comment by justingrounds** [comment]
Thank you for your reply Grant.

 

I’ll try out your recommendations.
