### ISSUE TITLE
start position

### ISSUE THREAD

**Issue by DIMAGORSH** [grantm/jquery-udraggable#18]
Hi.
I'm posting draggable elements from db. Each has its own start position (X and Y).
Guess, I have to specify "left" and "top" css properties after I start the script.
I'm trying to add:
`positionElement: function ($el, dragging, x, y) {
$el.css({top: '80px', left: '150px'});
},`
... but don't see the effect.
What is a correct way to give the draggable element certain start postion?

**Comment by grantm** [comment]
The positionElement method is only used during a drag operation, and is used to update the element's position on each mouse movement event.

At the start of a drag operation the position coordinates are calculated automatically based on where the element is on the page before the drag.

So if you're dynamically adding elements into the page, you just need to set their initial left and top directly via CSS as normal (i.e.: not using the udraggable plugin).

**Comment by DIMAGORSH** [comment]
Thanks. That was easy by using .each() and .css() functions just after your script.
You're right, the magic of your project is in its simplicity...
Great job. Good luck.
