### ISSUE TITLE
UDraggable prevents text selection outside draggable elements

### ISSUE THREAD

**Issue by noup** [grantm/jquery-udraggable#9]
First of all, thank you for writing this plugin, it's very useful.

I'm noticing an undesirable effect of using jquery-udraggable in our pages. After attaching it ao an element, one can no longer select text on the page by clicking somewhere, dragging, and doing mouse out somewhere else. Double-clicking a word, for example, does select it though.

This is especially problematic in input fields, as the user isn't able to select part of its text to be deleted.

**Comment by djkarimi** [comment]
Now I am doing guys?
Anyone solved this problem?
Please Help Me !!!
Go look this is link click : http://off.farazma.ir/ (Just Open Google Chrome ).

:(

**Comment by grantm** [comment]
I've applied a change to my version of the jquery.event.ue.js plugin used in the demo page: http://grantm.github.io/jquery-udraggable/examples/options.html

The modified file is:  http://grantm.github.io/jquery-udraggable/jquery.event.ue.js

Can you confirm whether this fixes your problem and whether it introduces any other problem?

**Comment by grantm** [comment]
Interestingly this problem finally appeared and directly affected me in Firefox 88 in April 2021. Simply upgrading to the latest (unmodified) version of jquery.event.ue.js from https://github.com/mmikowski/jquery.event.ue fixed the problem for me in both Firefox and Chrome.
